[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_distribution = "FXqAYUc17LzLQcrUuwd6XQHLT9TYNhiSopW878Kb92DN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/blockcode/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
